=== suslabs/el-levert/src/config/schemas/config.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "config",
    "title": "Config",
    "type": "object",
    "properties": {
        "logFile": {
            "type": "string"
        },
        "importLogFile": {
            "type": "string"
        },
        "eventsPath": {
            "type": "string"
        },
        "commandsPath": {
            "type": "string"
        },
        "cliCommandsPath": {
            "type": "string"
        },
        "dbPath": {
            "type": "string"
        },
        "logLevel": {
            "type": "string"
        },
        "cmdPrefix": {
            "type": "string"
        },
        "enableCliCommands": {
            "type": "boolean"
        },
        "cliCmdPrefix": {
            "type": "string"
        },
        "outCharLimit": {
            "type": "number"
        },
        "outLineLimit": {
            "type": "number"
        },
        "embedCharLimit": {
            "type": "number"
        },
        "embedLineLimit": {
            "type": "number"
        },
        "minResponseTime": {
            "type": "number"
        },
        "globalTimeLimit": {
            "type": "number"
        },
        "commandWaitTime": {
            "type": "number"
        },
        "reminderMsgLimit": {
            "type": "number"
        },
        "reminderSendInterval": {
            "type": "number"
        },
        "maxTagNameLength": {
            "type": "number"
        },
        "tagNameRegex": {
            "type": "string"
        },
        "maxTagSize": {
            "type": "number"
        },
        "maxQuota": {
            "type": "number"
        },
        "memLimit": {
            "type": "number"
        },
        "timeLimit": {
            "type": "number"
        },
        "otherMemLimit": {
            "type": "number"
        },
        "otherTimeLimit": {
            "type": "number"
        },
        "enableInspector": {
            "type": "boolean"
        },
        "enableUserInspector": {
            "type": "boolean"
        },
        "inspectorConnectTimeout": {
            "type": "number"
        },
        "userInspectorConnectTimeout": {
            "type": "number"
        },
        "userInspectorActionTimeout": {
            "type": "number"
        },
        "inspectorPort": {
            "type": "number"
        },
        "maxGroupNameLength": {
            "type": "number"
        },
        "tagModeratorLevel": {
            "type": "number"
        },
        "permissionAdminLevel": {
            "type": "number"
        },
        "enablePreviews": {
            "type": "boolean"
        },
        "enableSed": {
            "type": "boolean"
        },
        "enableEval": {
            "type": "boolean"
        },
        "enableOtherLangs": {
            "type": "boolean"
        },
        "enableVM2": {
            "type": "boolean"
        },
        "enablePermissions": {
            "type": "boolean"
        },
        "enableReminders": {
            "type": "boolean"
        },
        "enableGlobalHandler": {
            "type": "boolean"
        },
        "wrapEvents": {
            "type": "boolean"
        },
        "setActivity": {
            "type": "boolean"
        },
        "activity": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            },
            "required": ["type", "text"]
        },
        "mentionUsers": {
            "type": "boolean"
        },
        "pingReply": {
            "type": "boolean"
        },
        "logToDiscord": {
            "type": "boolean"
        },
        "discordLogLevel": {
            "type": "string"
        },
        "logChannelId": {
            "type": "string"
        },
        "logWebhook": {
            "type": "string"
        },
        "emoji": {
            "type": "object",
            "properties": {
                "info": { "type": "string" },
                "warn": { "type": "string" },
                "error": { "type": "string" },
                "ok": { "type": "string" },
                "invalid": { "type": "string" },
                "waiting": { "type": "string" }
            },
            "required": ["info", "warn", "error", "ok", "invalid", "waiting"]
        },
        "bridgeBotIds": {
            "type": "array"
        },
        "bridgeBotMessageFormat": {
            "type": "string"
        },
        "bridgeBotMessageFormats": {
            "oneOf": [
                {
                    "type": "array"
                },
                {
                    "type": "object"
                }
            ]
        }
    },
    "required": [
        "logFile",
        "importLogFile",
        "eventsPath",
        "commandsPath",
        "cliCommandsPath",
        "dbPath",
        "logLevel",
        "cmdPrefix",
        "enableCliCommands",
        "cliCmdPrefix",
        "outCharLimit",
        "outLineLimit",
        "embedCharLimit",
        "embedLineLimit",
        "minResponseTime",
        "globalTimeLimit",
        "commandWaitTime",
        "reminderMsgLimit",
        "reminderSendInterval",
        "maxTagNameLength",
        "tagNameRegex",
        "maxTagSize",
        "maxQuota",
        "memLimit",
        "timeLimit",
        "otherMemLimit",
        "otherTimeLimit",
        "enableInspector",
        "enableUserInspector",
        "inspectorConnectTimeout",
        "userInspectorConnectTimeout",
        "userInspectorActionTimeout",
        "inspectorPort",
        "maxGroupNameLength",
        "tagModeratorLevel",
        "permissionAdminLevel",
        "enablePreviews",
        "enableSed",
        "enableEval",
        "enableOtherLangs",
        "enableVM2",
        "enablePermissions",
        "enableReminders",
        "enableGlobalHandler",
        "wrapEvents",
        "setActivity",
        "activity",
        "mentionUsers",
        "pingReply",
        "logToDiscord",
        "discordLogLevel",
        "logChannelId",
        "logWebhook",
        "emoji",
        "bridgeBotIds"
    ],
    "anyOf": [{ "required": ["bridgeBotMessageFormat"] }, { "required": ["bridgeBotMessageFormats"] }]
}

=== suslabs/el-levert/config/config.json
{
    "logFile": "./logs/bot.log",
    "importLogFile": "./logs/import.log",
    "eventsPath": "./src/events",
    "commandsPath": "./src/commands",
    "cliCommandsPath": "./src/commands/cli",
    "dbPath": "./db",
    "logLevel": "debug",
    "cmdPrefix": "%",
    "enableCliCommands": true,
    "cliCmdPrefix": ".",
    "outCharLimit": 2000,
    "outLineLimit": 16,
    "embedCharLimit": 3000,
    "embedLineLimit": 40,
    "minResponseTime": 0.1,
    "globalTimeLimit": 60,
    "commandWaitTime": 3,
    "reminderMsgLimit": 512,
    "reminderSendInterval": 10,
    "maxTagNameLength": 32,
    "tagNameRegex": "^[A-Za-z0-9\\-_]+$",
    "maxTagSize": 100,
    "maxQuota": 1024,
    "memLimit": 250,
    "timeLimit": 15,
    "otherMemLimit": 50,
    "otherTimeLimit": 15,
    "enableInspector": true,
    "enableUserInspector": false,
    "inspectorConnectTimeout": 60,
    "userInspectorConnectTimeout": 30,
    "userInspectorActionTimeout": 300,
    "inspectorPort": 8080,
    "maxGroupNameLength": 16,
    "tagModeratorLevel": 1,
    "permissionAdminLevel": 2,
    "enablePreviews": true,
    "enableSed": true,
    "enableEval": true,
    "enableOtherLangs": false,
    "enableVM2": false,
    "enablePermissions": true,
    "enableReminders": true,
    "enableGlobalHandler": true,
    "wrapEvents": true,
    "setActivity": false,
    "activity": {
        "type": "watching",
        "text": "example"
    },
    "mentionUsers": false,
    "pingReply": true,
    "logToDiscord": false,
    "discordLogLevel": "info",
    "logChannelId": "",
    "logWebhook": "",
    "emoji": {
        "info": ":information_source:",
        "warn": ":warning:",
        "error": ":no_entry_sign:",
        "ok": ":white_check_mark:",
        "invalid": ":police_car:",
        "waiting": ":hourglass_flowing_sand:"
    },
    "bridgeBotIds": [],
    "bridgeBotMessageFormat": "\\*{2}.+?:\\*{2}\\s"
}
